# Generated by Django 4.0.1 on 2022-01-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_payment_orderitrm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItrm',
            new_name='OrderItem',
        ),
    ]
