# Generated by Django 4.0.1 on 2022-01-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_orderitrm_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quqntity',
            new_name='quantity',
        ),
    ]
