# Generated by Django 4.0.1 on 2022-01-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_quqntity_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='SizeVariant',
            new_name='sizeVariant',
        ),
        migrations.RenameField(
            model_name='tshirt',
            old_name='occation',
            new_name='occasion',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='image',
            field=models.ImageField(upload_to='upload/images/'),
        ),
    ]
